services:
  - name: beach-hangout
    type: web
    runtime: node
    region: oregon
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    buildCommand: npm install
    startCommand: node server.js
